"""Multimodal fusion API endpoints (Module 2.3).

Provides REST endpoints to trigger full fusion analysis on a session that
has already been processed by the vision and audio pipelines, check status,
and retrieve results, rubric scores, and narrative explanations.
"""

from __future__ import annotations

import logging
from uuid import UUID

from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.schemas.fusion import (
    ExplanationResultSchema,
    FusionProcessingResponse,
    FusionResultSchema,
    FusionStatusResponse,
    GroupRubricScoresSchema,
    StartFusionRequest,
)
from app.services.fusion_service import FusionService

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/sessions/{session_id}/analyze",
    response_model=FusionProcessingResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Start multimodal fusion analysis",
)
async def start_fusion_analysis(
    session_id: UUID,
    request: StartFusionRequest,
    db: AsyncSession = Depends(get_db),
) -> FusionProcessingResponse:
    """Enqueue a multimodal fusion task for the given analysis session.

    Both the vision and audio pipelines must have already completed for this
    session.  The task aligns temporal features, computes collaboration metrics,
    maps to UPAO rubric dimensions, and generates a narrative explanation.

    Returns immediately with a task ID that can be used to poll status.
    """
    service = FusionService(db)
    result = await service.start_analysis(
        session_id=session_id,
        config=request.config_overrides,
    )
    return FusionProcessingResponse(**result)


@router.get(
    "/sessions/{session_id}/status",
    response_model=FusionStatusResponse,
    summary="Check fusion analysis status",
)
async def get_fusion_status(
    session_id: UUID,
    db: AsyncSession = Depends(get_db),
) -> FusionStatusResponse:
    """Return the current status of a fusion processing task."""
    service = FusionService(db)
    status_info = await service.get_analysis_status(session_id)
    return FusionStatusResponse(**status_info)


@router.get(
    "/sessions/{session_id}/result",
    response_model=FusionResultSchema,
    summary="Get full fusion analysis result",
)
async def get_fusion_result(
    session_id: UUID,
    db: AsyncSession = Depends(get_db),
) -> FusionResultSchema:
    """Return the full fusion analysis result for a completed session.

    Returns 409 if the fusion analysis is not yet complete.
    """
    service = FusionService(db)
    result_data = await service.get_analysis_results(session_id)
    return FusionResultSchema(**result_data)


@router.get(
    "/sessions/{session_id}/explanation",
    response_model=ExplanationResultSchema,
    summary="Get narrative explanation",
)
async def get_fusion_explanation(
    session_id: UUID,
    db: AsyncSession = Depends(get_db),
) -> ExplanationResultSchema:
    """Return the narrative explanation for a completed fusion session.

    The explanation includes strengths, areas of improvement, and specific
    recommendations generated by the LLM (or rule-based fallback).
    """
    service = FusionService(db)
    explanation = await service.get_explanation(session_id)
    return ExplanationResultSchema(**explanation)


@router.get(
    "/sessions/{session_id}/rubric",
    response_model=GroupRubricScoresSchema,
    summary="Get UPAO rubric scores",
)
async def get_fusion_rubric(
    session_id: UUID,
    db: AsyncSession = Depends(get_db),
) -> GroupRubricScoresSchema:
    """Return the UPAO rubric scores for a completed fusion session.

    Scores are on a 0–20 scale across five dimensions: collaboration,
    communication, responsibility, leadership, and technical_contribution.
    """
    service = FusionService(db)
    rubric = await service.get_rubric_scores(session_id)
    return GroupRubricScoresSchema(**rubric)
