"""Pipeline de fusión multimodal (Módulo 2.3).

FusionPipeline orquesta las cuatro etapas de fusión:
  1. Alineación temporal    (TemporalAligner)
  2. Cálculo de métricas    (MetricsCalculator)
  3. Mapeo de rúbrica       (UPAORubricMapper)
  4. Generación de explicación (ExplanationGenerator)
"""

from __future__ import annotations

import logging
import time
from typing import Callable

from app.core.audio.data_types import AudioResult
from app.core.fusion.config import FusionConfig
from app.core.fusion.data_types import FusionResult
from app.core.fusion.explanation_generator import ExplanationGenerator
from app.core.fusion.metrics_calculator import MetricsCalculator
from app.core.fusion.rubric_mapper import UPAORubricMapper
from app.core.fusion.temporal_aligner import TemporalAligner
from app.core.vision.data_types import VisionResult

logger = logging.getLogger(__name__)


class FusionPipeline:
    def __init__(self, config: FusionConfig | None = None) -> None:
        self.config = config or FusionConfig()
        self._aligner = TemporalAligner(self.config)
        self._metrics = MetricsCalculator(self.config)
        self._mapper = UPAORubricMapper(self.config)
        self._explainer = ExplanationGenerator(self.config)

    def load_all(self) -> None:
        logger.debug("FusionPipeline.load_all() called (no-op)")

    def unload_all(self) -> None:
        logger.debug("FusionPipeline.unload_all() called (no-op)")

    def __enter__(self) -> "FusionPipeline":
        self.load_all()
        return self

    def __exit__(self, *args: object) -> None:
        self.unload_all()

    async def process(
        self,
        vision_result: VisionResult,
        audio_result: AudioResult,
        progress_callback: Callable[[float, str], None] | None = None,
    ) -> FusionResult:
        """Ejecuta el pipeline completo de fusión y retorna un FusionResult."""
        start_time = time.time()

        def _progress(p: float, msg: str) -> None:
            if progress_callback is not None:
                progress_callback(p, msg)

        _progress(0.0, "Starting temporal alignment")
        aligned = self._aligner.align(vision_result, audio_result)
        _progress(0.30, "Temporal alignment complete")
        logger.info(
            "Stage 1 complete: %d alignment windows, %d identity mappings",
            len(aligned.windows),
            len(aligned.speaker_to_person),
        )

        _progress(0.35, "Calculating student metrics")
        student_metrics = self._metrics.calculate_student_metrics(aligned, audio_result)
        _progress(0.55, "Calculating group metrics")
        group_metrics = self._metrics.calculate_group_metrics(
            aligned, audio_result, student_metrics
        )
        _progress(0.60, "Metrics calculation complete")
        logger.info(
            "Stage 2 complete: %d students, CV=%.3f, sync=%.2f",
            group_metrics.total_students,
            group_metrics.participation_cv,
            group_metrics.turn_synchronization_score,
        )

        _progress(0.65, "Mapping metrics to UPAO rubric")
        rubric_scores = self._mapper.map_group_to_rubric(group_metrics)
        _progress(0.75, "Rubric mapping complete")
        logger.info(
            "Stage 3 complete: collab=%.1f comm=%.1f resp=%.1f lead=%.1f tech=%.1f",
            rubric_scores.collaboration,
            rubric_scores.communication,
            rubric_scores.responsibility,
            rubric_scores.leadership,
            rubric_scores.technical_contribution,
        )

        _progress(0.80, "Generating narrative explanation")
        explanation = await self._explainer.generate(
            group_metrics, rubric_scores, audio_result
        )
        _progress(1.0, "Fusion analysis complete")
        logger.info(
            "Stage 4 complete: explanation generated by %s",
            explanation.generated_by,
        )

        processing_time = time.time() - start_time
        logger.info(
            "Fusion pipeline complete: %.1fs processing time (video duration %.1fs)",
            processing_time,
            aligned.duration_seconds,
        )

        return FusionResult(
            video_path=vision_result.video_path,
            aligned_features=aligned,
            group_metrics=group_metrics,
            rubric_scores=rubric_scores,
            explanation=explanation,
            processing_time_seconds=processing_time,
        )
